# Generated by Django 4.1.2 on 2022-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('socket', models.IntegerField()),
                ('frecuency', models.IntegerField()),
                ('boost_frec', models.IntegerField()),
                ('tdp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('chipset', models.CharField(max_length=20)),
                ('socket', models.IntegerField()),
                ('compatibility', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ram_Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('frecuency', models.IntegerField()),
                ('memory_cl', models.IntegerField()),
            ],
        ),
    ]
