# Generated by Django 4.1.2 on 2022-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('socket', models.CharField(max_length=10)),
                ('frecuency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('chipset', models.CharField(max_length=20)),
                ('socket', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RamMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('frecuency', models.CharField(max_length=10)),
            ],
        ),
    ]
